### ISSUE TITLE
Azerbaijani Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/az.reactjs.org#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the [glossary](https://github.com/reactjs/az.reactjs.org/blob/master/glossary.md) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [x] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@GasimGasimzada) #3
* [x] Tutorial (@GasimGasimzada) #5
* [x] Languages (@saidfagan) #41 
* [x] Release Channels (@GasimGasimzada) #150 

### Basics

* [x] Hello World (@Haqverdi) #8 
* [x] Introducing JSX (@Haqverdi) #27 
* [x] Rendering Elements (@GasimGasimzada) #89 
* [x] Components and Props (@azizaismayilova) #53 
* [x] State and Lifecycle (@saidfagan) #43 
* [x] Handling Events (@saidfagan) #50 
* [x] Conditional Rendering (@azizaismayilova) #77 
* [x] Lists and Keys (@GasimGasimzada) #94 
* [x] Forms (@GasimGasimzada) #90 
* [x] Lifting State Up (@GasimGasimzada) #92 
* [x] Composition vs Inheritance (@GasimGasimzada) #91 
* [x] Thinking in React (@GasimGasimzada) #93 

### API Reference

* [x] React (@GasimGasimzada) #47 
* [x] React.Component (@GasimGasimzada) #76 
* [x] ReactDOM (@GasimGasimzada) #78 
* [x] ReactDOMServer (@GasimGasimzada) #79 
* [x] DOM Elements (@GasimGasimzada) #80 
* [x] SyntheticEvent (@GasimGasimzada) #81 
* [x] Test Utilities (@GasimGasimzada) #82 
* [x] Shallow Renderer (@GasimGasimzada) #83 
* [x] Test Renderer (@GasimGasimzada) #85 
* [x] JS Environment Requirements (@GasimGasimzada) #84 
* [x] Glossary (@GasimGasimzada) #86 

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@GasimGasimzada) #5 
* [x] docs/nav.yml (@GasimGasimzada) #7 

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@GasimGasimzada) #103 
* [x] Add React to a Website (@GasimGasimzada) #107 
* [x] Create a New React App (@GasimGasimzada) #105 
* [x] CDN Links (@GasimGasimzada) #104 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@GasimGasimzada) #141 
  * [x] Hooks at a Glance (@GasimGasimzada) #140  
  * [x] Using the State Hook (@GasimGasimzada) #135 
  * [x] Using the Effect Hook (@GasimGasimzada) #137 
  * [x] Rules of Hooks (@GasimGasimzada) #136 
  * [x] Building Your Own Hooks (@GasimGasimzada) #142 
  * [x] Hooks API Reference (@GasimGasimzada) #143 
  * [x] Hooks FAQ (@GasimGasimzada) #145 

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] dont-call-proptypes (@GasimGasimzada) #112
* [x] invalid-aria-prop (@GasimGasimzada) #112
* [x] invalid-hook-call-warning (@GasimGasimzada) #147 
* [x] legacy-factories (@GasimGasimzada) #112
* [x] refs-must-have-owner (@GasimGasimzada) #112
* [x] special-props (@GasimGasimzada) #112
* [x] unknown-prop (@GasimGasimzada) #112

### Advanced Guides

* [x] Accessibility (@azizaismayilova) #12 
* [x] Code-Splitting (@GasimGasimzada) #21 
* [x] Context (@GasimGasimzada) #24 
* [x] Error Boundaries (@GasimGasimzada) #46 
* [x] Forwarding Refs (@azizaismayilova) #37 
* [x] Fragments (@azizaismayilova) #38 
* [x] Higher-Order Components (@mehdiyev) #99 
* [x] Integrating with Other Libraries (@GasimGasimzada) #101 
* [x] JSX In Depth (@GasimGasimzada) #114 
* [x] Optimizing Performance (@GasimGasimzada) #128 
* [x] Portals (@GasimGasimzada) #108 
* [x] Profiler (@GasimGasimzada) #129 
* [x] React Without ES6 (@GasimGasimzada) #117 
* [x] React Without JSX (@GasimGasimzada) #116 
* [x] Reconciliation (@GasimGasimzada) #127 
* [x] Refs and the DOM (@GasimGasimzada)
* [x] Render Props (@GasimGasimzada) #154 
* [x] Static Type Checking (@GasimGasimzada) #124 
* [x] Strict Mode (@GasimGasimzada) #125 
* [x] Typechecking With PropTypes (@GasimGasimzada) #119 
* [x] Uncontrolled Components (@GasimGasimzada) #121 
* [x] Web Components (@azizaismayilova) #39 

### FAQ

* [x] APIs and AJAX (@GasimGasimzada) #6 
* [x] Babel, JSX, and Build Steps (@GasimGasimzada) #111 
* [x] Passing Functions to Components (@GasimGasimzada) #130  
* [x] Component State (@GasimGasimzada) #123 
* [x] Styling and CSS (@GasimGasimzada) #115 
* [x] File Structure (@GasimGasimzada) #120 
* [x] Versioning Policy (@GasimGasimzada) #122 
* [x] Virtual DOM and Internals (@GasimGasimzada) #118 

### Testing

* [x] Overview (@GasimGasimzada) #131 
* [x] Testing Recipes (@GasimGasimzada) #134 
* [x] Testing Environment (@GasimGasimzada) #132 

### Concurrent Mode (Experimental)

* [x] Introducing Concurrent Mode (@mehdiyev) #178 
* [x] Suspense for Data Fetching (@GasimGasimzada) #171 
* [x] Concurrent UI Patterns (@GasimGasimzada) #172 
* [x] Adopting Concurrent Mode (@GasimGasimzada) #175 
* [x] Concurrent Mode API Reference (@GasimGasimzada) #176 

### Contributing

Priority: Low

* [x] How to Contribute (@GasimGasimzada) #160 
* [x] Codebase Overview (@GasimGasimzada) #166 
* [x] Implementation Notes (@GasimGasimzada) #168 
* [x] Design Principles (@mehdiyev) #169 

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor (@GasimGasimzada)
* [x] CodeExample (@GasimGasimzada)
* [x] ErrorDecoder (@GasimGasimzada) #149 
* [x] LayoutFooter (@GasimGasimzada)
* [x] LayoutHeader (@GasimGasimzada)
* [x] MarkdownPage (@GasimGasimzada)

### Other

* [x] Community (@GasimGasimzada) #177 

### Config

* [x] Gatsby Config file (@GasimGasimzada) #148

**Comment by Haqverdi** [comment]
Of course I want to translate everything, but let's start with the first page, that is `Home Page`

**Comment by GasimGasimzada** [comment]
@Haqverdi choose a page that you would like to work on and I will assign you the task in this issue. I am currently doing Homepage and Tutorial.

**Comment by Haqverdi** [comment]
> @Haqverdi choose a page that you would like to work on and I will assign you the task in this issue. I am currently doing Homepage and Tutorial.

okay, then i will work on Hello World Page

**Comment by GasimGasimzada** [comment]
I have added you to "Hello World" checklist item. Also, please refer to the glossary of terms when translating to have consistency across translations (it is still in Work in Progress but we are getting there :)).

**Comment by Haqverdi** [comment]
First of all, I am very glad that besides me from Azerbaijan, someone is using a react and ecosystem and with the desire that others could also use
GasimGasimzada are you member or contrubitor?

**Comment by GasimGasimzada** [comment]
Member

**Comment by GasimGasimzada** [comment]
@Haqverdi any progress on "Introducing JSX"?

**Comment by Haqverdi** [comment]
> @Haqverdi any progress on "Introducing JSX"?

today, will complete, hope

**Comment by saidfagan** [comment]
Hi guys. I would like to participate in the translation process, too. I want to translate the small _Languages_ page for a start.

**Comment by GasimGasimzada** [comment]
@saidfagan I would suggest you start with the basics "State and Lifecycle" but you can also start from Languages page. Just fork the repo and send us a PR and we will merge it once everything is in order.

**Comment by saidfagan** [comment]
OK. Then please assign me _State and Lifecycle_ page.

**Comment by Haqverdi** [comment]
> OK. Then please assign me _State and Lifecycle_ page.

done

**Comment by mehdiyev** [comment]
> ## For New Translators
> To translate a page:
> 
> 1. Check that no one else has claimed your page in the checklist and comments below.
> 2. Comment below with the name of the page you would like to translate. **Take only one page at a time**.
> 3. Clone this repo, translate your page, and submit a pull request!
> 
> Before contributing, read the glossary to understand how to translate various technical and React-specific terms.
> 
> You can use the [Crowdin](https://crowdin.com/project/react) as a base for your translation. Make sure to compare the content with the current React website to makes sure everything is up to date! (NOTE: delete this if the language doesn't have any Crowdin contributions)
> 
> Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.
> 
> ## For maintainers
> When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:
> 
> * [ ]  Home Page (@tesseralis) #1
> 
> When PRs are merged, make sure to mark that page as completed!
> 
> ## Core Pages
> To do before releasing as an "official" translation. **Please translate these pages first.**
> 
> * [x]  Home Page (@GasimGasimzada)
> * [x]  Tutorial (@GasimGasimzada)
> * [x]  Languages (@saidfagan)
> 
> ### Basics
> * [x]  Hello World (@Haqverdi)
> * [x]  Introducing JSX (@Haqverdi)
> * [ ]  Rendering Elements (@Haqverdi)
> * [ ]  Components and Props (@azizaismayilova)
> * [ ]  State and Lifecycle (@saidfagan) - Awaiting Review
> * [ ]  Handling Events
> * [ ]  Conditional Rendering
> * [ ]  Lists and Keys
> * [ ]  Forms
> * [ ]  Lifting State Up
> * [ ]  Composition vs Inheritance
> * [ ]  Thinking in React
> 
> ### API Reference
> * [ ]  React
> * [ ]  React.Component
> * [ ]  ReactDOM
> * [ ]  ReactDOMServer
> * [ ]  DOM Elements
> * [ ]  SyntheticEvent
> * [ ]  Test Utilities
> * [ ]  Shallow Renderer
> * [ ]  Test Renderer
> * [ ]  JS Environment Requirements
> * [ ]  Glossary
> 
> ### Navigation
> These are the navigation links that appears in the sidebar. Possibly wait until
> the corresponding sections are translated to do these.
> 
> * [x]  tutorial/nav.yml (@GasimGasimzada )
> * [x]  docs/nav.yml (@GasimGasimzada)
> 
> ## Next Steps
> These are the next most important translations, ordered by importance:
> 
> ### Installation
> * [ ]  Getting Started
> * [ ]  Add React to a Website
> * [ ]  Create a New React App
> * [ ]  CDN Links
> 
> ### Hooks
> Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.
> 
> * [ ]  Introducing Hooks
> * [ ]  Hooks at a Glance
> * [ ]  Using the State Hook
> * [ ]  Using the Effect Hook
> * [ ]  Rules of Hooks
> * [ ]  Building Your Own Hooks
> * [ ]  Hooks API Reference
> * [ ]  Hooks FAQ
> 
> ### Warnings
> These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
> 
> * [ ]  dont-call-proptypes
> * [ ]  invalid-aria-prop
> * [ ]  invalid-hook-call-warning
> * [ ]  legacy-factories
> * [ ]  refs-must-have-owner
> * [ ]  special-props
> * [ ]  unknown-prop
> 
> ### Advanced Guides
> * [x]  Accessibility (@azizaismayilova)
> * [x]  Code-Splitting (@GasimGasimzada)
> * [ ]  Context (@GasimGasimzada) - Awaiting Review
> * [ ]  Error Boundaries (@GasimGasimzada)
> * [ ]  Forwarding Refs (@azizaismayilova ) - Awaiting Review
> * [ ]  Fragments (@azizaismayilova)  - Awaiting Review
> * [ ]  Higher-Order Components (@mehdiyev)
> * [ ]  Integrating with Other Libraries
> * [ ]  JSX In Depth
> * [ ]  Optimizing Performance
> * [ ]  Portals
> * [ ]  React Without ES6
> * [ ]  React Without JSX
> * [ ]  Reconciliation
> * [ ]  Refs and the DOM
> * [ ]  Render Props
> * [ ]  Static Type Checking
> * [ ]  Strict Mode
> * [ ]  Typechecking With PropTypes
> * [ ]  Uncontrolled Components
> * [ ]  Web Components (@azizaismayilova) - Awaiting Review
> 
> ### FAQ
> * [x]  APIs and AJAX (@GasimGasimzada)
> * [ ]  Babel, JSX, and Build Steps
> * [ ]  Passing Functions to Components
> * [ ]  Component State
> * [ ]  Styling and CSS
> * [ ]  File Structure
> * [ ]  Versioning Policy
> * [ ]  Virtual DOM and Internals
> 
> ### Contributing
> Priority: Low
> 
> * [ ]  How to Contribute
> * [ ]  Codebase Overview
> * [ ]  Implementation Notes
> * [ ]  Design Principles
> 
> ### Components
> Components in `src/components` that have some text in them.
> 
> * [x]  CodeEditor (@GasimGasimzada)
> * [x]  CodeExample (@GasimGasimzada)
> * [ ]  ErrorDecoder
> * [x]  LayoutFooter (@GasimGasimzada)
> * [x]  LayoutHeader (@GasimGasimzada)
> * [ ]  MarkdownPage
> 
> ## Additional Translations
> These are not the primary translation targets.
> 
> * [ ]  Blog
> * [ ]  Community

**Comment by GasimGasimzada** [comment]
@mehdiyev Hello, are you going to be doing "Higher Order Components"?

**Comment by mehdiyev** [comment]
@GasimGasimzada yes please, assign me to _HOC_ page

**Comment by GasimGasimzada** [comment]
In the future, when wanting to do certain translation, please comment here; so that, we know what is everyone working on.

**Comment by azizaismayilova** [comment]
@Haqverdi any updates on Rendering Elements?

**Comment by GasimGasimzada** [comment]
@Haqverdi could you please provide us with a time frame on when you are going to finish "Rendering Elements"?

@saidfagan is there another translation that you want to pick up on? If you do, please comment here and I will assign your name here.

**Comment by Haqverdi** [comment]
I am very sorry for the fact that I could not answer for a long time, approximately it will be possible in a week

**Comment by GasimGasimzada** [comment]
Great! Thank you for the update!

**Comment by saidfagan** [comment]
_Handling Events_, please

**Comment by azizaismayilova** [comment]
@saidfagan assigned you to "Handling Events"

**Comment by GasimGasimzada** [comment]
I have taken `React.Component` API Reference

**Comment by GasimGasimzada** [comment]
@saidfagan could you start working on "Rendering Elements" page?

**Comment by saidfagan** [comment]
> 
> 
> @saidfagan could you start working on "Rendering Elements" page?

Yes, please

**Comment by GasimGasimzada** [comment]
Done!

**Comment by azizaismayilova** [comment]
@mehdiyev any updates on HOC?

**Comment by GasimGasimzada** [comment]
@saidfagan @azizaismayilova @Haqverdi 

I have finished 10 translations (all “API Reference” and 1 translation left in “Core Concepts”). They are all available in Pull Requests. Could you please review the translations for anything I may have missed (grammatical, syntactical, doesn’t matter)? Each PR has a link in it (deploy-X.netlify.com). By following the link, you can find the changes by navigating to the appropriate documentation.

**You can write your review in Azerbaijani.** There is no restriction on what language you use to write your reviews as long as we can read and fix the changes :)

If you do review, just comment here on which PR you will be working on; so that, two people do not end up reviewing the same thing.

—

If you do review and find mistakes, in the PR, please create a list with line numbers. If mistake is a 1-2 words, please make the mistakes bold. For example, let’s say that I have written “Anket sahəsində olan dəyəri müəyənləşdirmək lazımdır” (one “y”) in line 130. In order to show the mistakes, the list will look like the following:

- [ ] Line 130: dəyəri **müəyənləşdirmək** lazımdır

**Comment by mehdiyev** [comment]
> @mehdiyev any updates on HOC?

I have finished translation.  Sorry for late response

**Comment by GasimGasimzada** [comment]
@mehdiyev it is going to take a while to review your PR since we have 7 more PRs in queue, waiting to be reviewed. If you would like to work on another page, please check the the list above and without a name and let us know. Currently, the main focus is translating “Advanced Guides.” So, choose any unassigned item from the list and comment here; so, I can add your name next to the item to avoid potential conflicts.

**Comment by mehdiyev** [comment]
@GasimGasimzada okay, then assign me _Refs and the DOM_ page, please.

**Comment by GasimGasimzada** [comment]
Done

**Comment by GasimGasimzada** [comment]
@mehdiyev any info on Refs and the DOM page?

**Comment by GasimGasimzada** [comment]
Additionally, glossary is now moved to a file: https://github.com/reactjs/az.reactjs.org/blob/master/glossary.md. You can click glossary button in this issue or at the top of the README file.

**Comment by mehdiyev** [comment]
> @mehdiyev any info on Refs and the DOM page?

This weekend planning to open PR.

**Comment by mehdiyev** [comment]
Can you please assign me Design Principles page? 
Btw, sorry for not getting back with refs&dom page. I did not make it in time.

**Comment by GasimGasimzada** [comment]
Done! Please finish it by Friday.

**Comment by mehdiyev** [comment]
I would like to start with "CONCURRENT MODE" phase. Can you assign me please?

**Comment by GasimGasimzada** [comment]
Done!

**Comment by GasimGasimzada** [comment]
@mehdiyev any updates on Concurrent Mode Intro?

**Comment by GasimGasimzada** [comment]
@mehdiyev If you can't finish it by tomorrow, I am going to assign Concurrent Mode Intro to myself.

**Comment by mehdiyev** [comment]
@GasimGasimzada almost done. Tomorrow I'll open PR.

**Comment by GasimGasimzada** [comment]
Thank you everyone for your contributions. Since we have reached 100%, it is time to close this issue 🎉

**Comment by gaearon** [comment]
Hi folks,

Just a heads-up that we've done our best to bring `main` and `legacy` branches up-to-date with upstream. This brings you to the latest visual design and sets up all the redirects. We don't anticipate more changes necessary on `legacy`. For `main`, there's a few things you need to be aware of:

- Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.
- The homepage is untranslated so ideally it would be good if you could do a pass at that. For now, unfortunately it requires messing with the code file.

Thank you so much for your cooperation!

**Comment by gaearon** [comment]
Opened an issue for the new translation: https://github.com/reactjs/az.react.dev/issues/376
